services:
  mongodb:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d

  apache:
    build: ./apache-php
    container_name: apache2
    ports:
      - "8080:80"
    volumes:
      - ./apache-php/app:/var/www/html